### ISSUE TITLE
Error: Cannot find module './build/Release/shell'

### ISSUE THREAD

**Issue by vinnitu** [G33kLabs/node-tts-speak#1]
What is missing?

```
$ node tts-google.js 
[12:43:33 PM] [tts-speak] Detect tts engine...
[[12:43:33 PM] [tts-speak] TTS engine found : google
[12:43:33 PM] [tts-speak] Detect speak engine...
module.js:338
    throw err;
          ^
Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/victor/projects/twitter-tts/node_modules/tts-speak/node_modules/find-exec/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by G33kLabs** [comment]
There was a problem with one of the package I used 'find-exec'.
I've removed the dependency, so in order to work, check at the examples, you've to change 'auto' to 'mplayer'

```
var speak = new Speak({
    tts: {
        engine: 'google',               // The engine to use for tts
        lang: 'en-us',                  // The voice to use
        cache: __dirname + '/cache',    // The cache directory were audio files will be stored
        loglevel: 0,                    // TTS log level (0: trace -> 5: fatal)
        delayAfter: 500                 // Mark a delay (ms) after each message
    },
    speak: {
        engine: 'mplayer',                 // Auto select the audio player
        volume: 100,                    // Volume in %
        loglevel: 0                     // Audio player log level
    },
    loglevel: 0                         // Wrapper log level
});
```

And don't forget to update the package, the version is now "0.9.8"

**Comment by G33kLabs** [comment]
Sorry... bullshits, it's been a long time and I don't need no more this because now I use 'speaker' package...
Please wait a moment...
